# Generated by Django 4.1.5 on 2023-01-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='defaultcarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=400, null=True, upload_to='home/defaultslider/')),
                ('imgtitle', models.CharField(max_length=100)),
                ('imginto', models.CharField(max_length=100)),
            ],
        ),
    ]
