# Generated by Django 4.1.5 on 2023-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_servicecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecard',
            name='imginto',
            field=models.CharField(max_length=300),
        ),
    ]
