# Generated by Django 4.1.5 on 2023-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_servicecard_imginto'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecard',
            name='link',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='imginto',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='imgtitle',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
